version: "3.8"

services:
  broker:
    image: eclipse-mosquitto
    hostname: broker
    ports:
      - "1883:1883"
    volumes:
      - ./broker:/mosquitto/config
    # restart: unless-stopped
    user: 1000:1000

  bridge:
    image: eclipse-mosquitto
    hostname: bridge
    ports:
      - "1884:1883"
    volumes:
      - ./bridge:/mosquitto/config
    # restart: unless-stopped
    user: 1000:1000
    depends_on:
      broker:
        condition: service_started
        restart: true
